import {test,expect} from "@playwright/test";
import sharp from "sharp";
test("upload, verify, replace, edit alt text and delete unused media",async({page})=>{
await page.goto("/admin/login");await page.getByLabel("Email",{exact:true}).fill(process.env.ADMIN_EMAIL!);await page.getByLabel("Password",{exact:true}).fill(process.env.ADMIN_PASSWORD!);await page.getByRole("button",{name:"Enter Studio →"}).click();await expect(page).toHaveURL(/\/admin\/projects$/);await page.goto("/admin/media");
const name="browser-upload-"+Date.now()+".png";const bytes=await sharp({create:{width:320,height:240,channels:3,background:"#637568"}}).png().toBuffer();
await page.getByRole("button",{name:"+ Upload",exact:true}).click();await page.locator('input[type="file"]').setInputFiles({name,mimeType:"image/png",buffer:bytes});await expect(page.getByText(/1 image\(s\) uploaded/)).toBeVisible({timeout:15000});await page.getByRole("button",{name:"Close dialog"}).click();
let card=page.locator("article.media-tile").filter({hasText:name});await card.hover();await card.getByRole("button",{name:"Details",exact:true}).click();await expect(page.getByText(/320 × 240/)).toBeVisible();await page.getByLabel("Alt text",{exact:true}).fill("Green rectangular test artwork");await page.getByRole("button",{name:"Save alt text",exact:true}).click();await expect(page.getByText("Alt text saved.",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Close dialog"}).click();await page.reload();await card.hover();await card.getByRole("button",{name:"Details",exact:true}).click();await expect(page.getByLabel("Alt text",{exact:true})).toHaveValue("Green rectangular test artwork");await page.getByRole("button",{name:"Close dialog"}).click();await expect.poll(()=>card.locator("img").evaluate((i:HTMLImageElement)=>i.naturalWidth)).toBeGreaterThan(0);
await card.hover();await card.getByRole("button",{name:"Replace",exact:true}).click();const replacement="replacement-"+name;await page.locator('input[type="file"]').setInputFiles({name:replacement,mimeType:"image/png",buffer:bytes});await expect(page.getByRole("dialog")).toHaveCount(0,{timeout:15000});card=page.locator("article.media-tile").filter({hasText:replacement});await card.hover();await card.getByRole("button",{name:"Details",exact:true}).click();await expect(page.getByLabel("Alt text",{exact:true})).toHaveValue("Green rectangular test artwork");await page.getByRole("button",{name:"Close dialog"}).click();
await card.hover();page.once("dialog",d=>d.accept(replacement));await card.getByRole("button",{name:"Delete",exact:true}).click();await expect(card).toHaveCount(0);const sample=page.locator("article.media-tile").filter({hasText:"sample-nightshift.svg"});await sample.hover();await expect(sample.getByRole("button",{name:"Delete",exact:true})).toBeDisabled();
await page.getByRole("button",{name:"+ Upload",exact:true}).click();await page.locator('input[type="file"]').setInputFiles({name:"invalid.png",mimeType:"image/png",buffer:Buffer.from("This is not an image")});await expect(page.getByText(/Upload failed/)).toBeVisible();await expect(page.locator("article.media-tile").filter({hasText:"invalid.png"})).toHaveCount(0);
});
