import "dotenv/config";
import {chromium} from "@playwright/test";
import {mkdirSync,writeFileSync,readFileSync} from "node:fs";
import {createHash} from "node:crypto";
const out=".local/visual-qa";mkdirSync(out,{recursive:true});
const browser=await chromium.launch();const page=await browser.newPage();const errors=[];page.on("pageerror",e=>errors.push(e.message));
await page.goto("http://localhost:3000/admin/login");
await page.getByLabel("Email",{exact:true}).fill(process.env.ADMIN_EMAIL);
await page.getByLabel("Password",{exact:true}).fill(process.env.ADMIN_PASSWORD);
await page.getByRole("button",{name:"Enter Studio →"}).click();await page.waitForURL("**/admin/projects");
const editPath=await page.locator(".t-title").first().getAttribute("href");
await page.goto("http://localhost:3000/work");const detailPath=await page.locator(".archive-item").first().getAttribute("href");
const routes=[["home","/"],["archive","/work"],["index","/work?view=index"],["detail",detailPath],["about","/about"],["contact","/contact"],["login","/admin/login"],["projects","/admin/projects"],["new","/admin/projects/new"],["edit",editPath],["media","/admin/media"],["settings","/admin/settings"],["preview","/admin/preview/"+editPath.split("/").pop()]];
const report=[];for(const width of [1440,1024,390]){await page.setViewportSize({width,height:900});for(const[name,path]of routes){const response=await page.goto("http://localhost:3000"+path);await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(800);await page.screenshot({path:out+"/"+name+"-"+width+".png",fullPage:true});report.push({name,width,status:response.status(),...await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,font:getComputedStyle(document.querySelector("h1")).fontFamily,heading:getComputedStyle(document.querySelector("h1")).fontSize,images:[...document.images].filter(i=>i.getBoundingClientRect().height>0).map(i=>({loaded:i.complete&&i.naturalWidth>0,alt:i.alt}))}))})}console.log("Production screenshots complete: "+width)}
const reference=await browser.newPage();await reference.setViewportSize({width:1440,height:900});for(const width of [1440,1024,390]){await reference.setViewportSize({width,height:900});for(const[name,hash]of [["home","/"],["archive","/work"],["detail","/project/nightshift"],["about","/about"],["contact","/contact"]]){await reference.goto("http://127.0.0.1:3001/public-site.html#"+hash);await reference.evaluate(()=>document.fonts.ready);await reference.waitForTimeout(1100);await reference.screenshot({path:out+"/reference-"+name+"-"+width+".png",fullPage:true})}await reference.goto("http://127.0.0.1:3001/admin.html");await reference.evaluate(()=>document.fonts.ready);await reference.screenshot({path:out+"/reference-login-"+width+".png",fullPage:true});await reference.locator("#loginForm").evaluate(f=>f.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true})));for(const[name,screen]of [["projects","dashboard"],["edit","editor"],["media","media"],["settings","settings"]]){if(screen!=="dashboard"){const b=reference.locator('[data-screen="'+screen+'"]').first();if(await b.count())await b.click();else await reference.locator(".row-actions button").first().click()}await reference.screenshot({path:out+"/reference-"+name+"-"+width+".png",fullPage:true})}console.log("Reference screenshots complete: "+width)}
writeFileSync(out+"/report.json",JSON.stringify({report,errors,designHashes:Object.fromEntries(["public-site.html","admin.html","design-system.md"].map(f=>[f,createHash("sha256").update(readFileSync("design/"+f)).digest("hex")]))},null,2));await browser.close();console.log(JSON.stringify({pages:report.length,overflow:report.filter(r=>r.overflow),errors}));
